### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kubeworkz** [benallfree/pockethost#105]
I get the following error when running migrate-dev.yml
```
osboxes@osboxes:~/pockethost$ docker-compose -f docker/migrate-dev.yaml up --remove-orphans
Removing orphan container "build"
Building prepbox
Sending build context to Docker daemon  24.43MB
Step 1/4 : FROM node:18-alpine as pockethost-buildbox
 ---> 0fa08f92e64b
Step 2/4 : COPY --from=golang:1.19.3-alpine /usr/local/go/ /usr/local/go/
 ---> Using cache
 ---> 72e06e159c81
Step 3/4 : ENV PATH="/usr/local/go/bin:${PATH}"
 ---> Using cache
 ---> e786ac77833f
Step 4/4 : RUN apk add python3 py3-pip make gcc musl-dev g++ bash sqlite
 ---> Using cache
 ---> bcad43604315
Successfully built bcad43604315
Successfully tagged docker_prepbox:latest
WARNING: Image for service prepbox was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating prepbox ... done
Attaching to prepbox
prepbox    | yarn run v1.22.19
prepbox    | $ yarn migrate:daemon
prepbox    | $ cd packages/daemon && yarn migrate
prepbox    | $ tsx src/migrate/migrate.ts
prepbox    | {
prepbox    |   instanceId: 'pockethost-central',
prepbox    |   dataRoot: '/data/pockethost-central',
prepbox    |   backupTgzRoot: '/data/pockethost-central/backup',
prepbox    |   backupTgzFile: '/data/pockethost-central/backup/1668715795355.tgz',
prepbox    |   backupTmpTargetRoot: '/tmp/tmp-61-60NrP8DU2FLS'
prepbox    | }
prepbox    | Error: ENOENT: no such file or directory, chdir '/src/packages/daemon' -> '/data/pockethost-central'
prepbox    | Removing again /tmp/tmp-61-60NrP8DU2FLS
prepbox    | backupInstance:1 failed: Error: ENOENT: no such file or directory, chdir '/src/packages/daemon' -> '/data/pockethost-central'
prepbox    | backupInstance:1 Error: ENOENT: no such file or directory, chdir '/src/packages/daemon' -> '/data/pockethost-central'
prepbox    |     at wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:112:14)
prepbox    |     at process.chdir (node:internal/worker:99:5)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/backupInstance.ts:88:7)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/safeAsync.ts:42:12)
prepbox    |     at <anonymous> (/src/packages/daemon/src/migrate/migrate.ts:18:9)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/safeAsync.ts:42:12)
prepbox    |     at <anonymous> (/src/packages/daemon/src/migrate/migrate.ts:45:2)
prepbox    |     at Object.<anonymous> (/src/packages/daemon/src/migrate/migrate.ts:45:4)
prepbox    |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
prepbox    |     at Object.v (/src/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901) {
prepbox    |   errno: -2,
prepbox    |   code: 'ENOENT',
prepbox    |   syscall: 'chdir',
prepbox    |   path: '/src/packages/daemon',
prepbox    |   dest: '/data/pockethost-central'
prepbox    | }
prepbox    | root:0 failed: Error: ENOENT: no such file or directory, chdir '/src/packages/daemon' -> '/data/pockethost-central'
prepbox    | root:0 Error: ENOENT: no such file or directory, chdir '/src/packages/daemon' -> '/data/pockethost-central'
prepbox    |     at wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:112:14)
prepbox    |     at process.chdir (node:internal/worker:99:5)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/backupInstance.ts:88:7)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/safeAsync.ts:42:12)
prepbox    |     at <anonymous> (/src/packages/daemon/src/migrate/migrate.ts:18:9)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/safeAsync.ts:42:12)
prepbox    |     at <anonymous> (/src/packages/daemon/src/migrate/migrate.ts:45:2)
prepbox    |     at Object.<anonymous> (/src/packages/daemon/src/migrate/migrate.ts:45:4)
prepbox    |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
prepbox    |     at Object.v (/src/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901) {
prepbox    |   errno: -2,
prepbox    |   code: 'ENOENT',
prepbox    |   syscall: 'chdir',
prepbox    |   path: '/src/packages/daemon',
prepbox    |   dest: '/data/pockethost-central'
prepbox    | }
prepbox    | node:internal/process/promises:288
prepbox    |             triggerUncaughtException(err, true /* fromPromise */);
prepbox    |             ^
prepbox    | 
prepbox    | Error: ENOENT: no such file or directory, chdir '/src/packages/daemon' -> '/data/pockethost-central'
prepbox    |     at wrappedChdir (node:internal/bootstrap/switches/does_own_process_state:112:14)
prepbox    |     at process.chdir (node:internal/worker:99:5)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/backupInstance.ts:88:7)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/safeAsync.ts:42:12)
prepbox    |     at <anonymous> (/src/packages/daemon/src/migrate/migrate.ts:18:9)
prepbox    |     at <anonymous> (/src/packages/daemon/src/util/safeAsync.ts:42:12)
prepbox    |     at <anonymous> (/src/packages/daemon/src/migrate/migrate.ts:45:2)
prepbox    |     at Object.<anonymous> (/src/packages/daemon/src/migrate/migrate.ts:45:4)
prepbox    |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
prepbox    |     at Object.v (/src/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901) {
prepbox    |   errno: -2,
prepbox    |   code: 'ENOENT',
prepbox    |   syscall: 'chdir',
prepbox    |   path: '/src/packages/daemon',
prepbox    |   dest: '/data/pockethost-central'
prepbox    | }
prepbox    | 
prepbox    | Node.js v18.12.1
prepbox    | error Command failed with exit code 1.
prepbox    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
prepbox    | error Command failed with exit code 1.
prepbox    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
prepbox    | error Command failed with exit code 1.
prepbox    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
prepbox exited with code 1
```

**Comment by benallfree** [comment]
Hi, I think this is happening because there is no `pockethost-central` instance yet. I'll keep this issue open until I solve it, but in the mean time, try creating `./docker/mount/daemon/instances/pockethost-central` and then run `pocketbase` manually once inside there to create the databases.

**Comment by kubeworkz** [comment]
Thanks

**Comment by benallfree** [comment]
Closing because Docker is gone now.
